<a href="https://colab.research.google.com/github/amaldevice/DAProjectCaseStudy/blob/main/DAProject2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Import / Data Wrangling

This data is taken from kaggle in 4 csv table format and combined in Google BigQuery SQL. In Python i will do several stages of transformation and data cleaning.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("/content/bq-results-20230901-162707-1693587876343.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178519 entries, 0 to 178518
Data columns (total 23 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   order_id         178519 non-null  int64
 1   seller_id        178519 non-null  int64
 2   buyer_id         178519 non-null  int64
 3   kodepos          178519 non-null  int64
 4   subtotal         178519 non-null  int64
 5   discount         178519 non-null  int64
 6   total            178519 non-null  int64
 7   created_at       178519 non-null  object
 8   paid_at          166565 non-null  object
 9   delivery_at      155313 non-null  object
 10  order_detail_id  178519 non-null  int64
 11  order_id_1       178519 non-null  int64
 12  product_id       178519 non-null  int64
 13  price            178519 non-null  int64
 14  quantity         178519 non-null  int64
 15  product_id_1     178519 non-null  int64
 16  desc_product     178519 non-null  object
 17  category         178519 non-null  object
 18  base_price       178519 non-null  int64
 19  user_id          178519 non-null  int64
 20  nama_user        178519 non-null  object
 21  kodepos_1        178519 non-null  int64
 22  email            178519 non-null  object
dtypes: int64(16), object(7)
memory usage: 31.3+ MB

In [3]:
df.head()

,order_id,seller_id,buyer_id,kodepos,subtotal,discount,total,created_at,paid_at,delivery_at,...,price,quantity,product_id_1,desc_product,category,base_price,user_id,nama_user,kodepos_1,email
0,209089,44,3871,44770,6816000,0,6816000,2020-02-29,2020-03-08,2020-03-08,...,14000,7,872,Pucelle Body Mist Cologne Wavy Ocean 150Ml,Kebersihan Diri,14000,3871,Hendri Palastri,44770,dipa04@hotmail.com
1,209089,44,3871,44770,6816000,0,6816000,2020-02-29,2020-03-08,2020-03-08,...,28000,16,1122,Natur-E Hand Body Lotion 245Ml,Kebersihan Diri,28000,3871,Hendri Palastri,44770,dipa04@hotmail.com
2,209089,44,3871,44770,6816000,0,6816000,2020-02-29,2020-03-08,2020-03-08,...,165000,38,597,Blackmores Pregnancy & Breast-Feeding Gold 60's,Vitamin,165000,3871,Hendri Palastri,44770,dipa04@hotmail.com
3,51393,55,699,84712,5440000,0,5440000,2020-03-15,2020-03-17,2020-03-25,...,85000,32,13,BLANIK BLOUSE BL023,Pakaian Wanita,85000,699,"Rahmi Hutapea, S.Farm",84712,bancarmandala@yahoo.com
4,51393,55,699,84712,5440000,0,5440000,2020-03-15,2020-03-17,2020-03-25,...,85000,32,13,BLANIK BLOUSE BL023,Pakaian Wanita,85000,699,"Rahmi Hutapea, S.Farm",84712,bancarmandala@yahoo.com

In [4]:
df.describe()

,order_id,seller_id,buyer_id,kodepos,subtotal,discount,total,order_detail_id,order_id_1,product_id,price,quantity,product_id_1,base_price,user_id,kodepos_1
count,178519.000000,178519.000000,178519.000000,178519.000000,1.785190e+05,1.785190e+05,1.785190e+05,1.785190e+05,178519.000000,178519.000000,178519.000000,178519.000000,178519.000000,178519.000000,178519.000000,178519.000000
mean,250300.352495,35.032882,9002.513083,50088.876013,2.887947e+06,2.306598e+04,2.862055e+06,8.972884e+05,250300.352495,576.442127,37382.043368,22.471905,576.442127,37382.043368,9002.513083,49671.588442
std,143963.647575,19.915448,5163.981954,28858.354042,3.186781e+06,1.332670e+05,3.160099e+06,5.164709e+05,143963.647575,329.588161,45635.842991,11.536522,329.588161,45635.842991,5163.981954,29028.798561
min,3.000000,1.000000,1.000000,0.000000,6.000000e+03,0.000000e+00,6.000000e+03,5.000000e+00,3.000000,1.000000,2000.000000,3.000000,1.000000,2000.000000,1.000000,0.000000
25%,125076.000000,18.000000,4552.000000,25104.000000,7.100000e+05,0.000000e+00,7.020000e+05,4.472945e+05,125076.000000,288.000000,8000.000000,12.000000,288.000000,8000.000000,4552.000000,24344.500000
50%,251092.000000,35.000000,9011.000000,50005.000000,1.830000e+06,0.000000e+00,1.814000e+06,8.999480e+05,251092.000000,581.000000,20000.000000,22.000000,581.000000,20000.000000,9011.000000,49221.000000
75%,374313.000000,52.000000,13470.000000,75015.500000,3.945000e+06,0.000000e+00,3.909000e+06,1.342334e+06,374313.000000,861.000000,48000.000000,32.000000,861.000000,48000.000000,13470.000000,74912.000000
max,498783.000000,69.000000,17936.000000,99997.000000,3.611400e+07,4.602000e+06,3.611400e+07,1.789270e+06,498783.000000,1145.000000,365000.000000,42.000000,1145.000000,365000.000000,17936.000000,99997.000000

In [5]:
df.duplicated().sum()

0

In [6]:
df.isna().sum()

order_id               0
seller_id              0
buyer_id               0
kodepos                0
subtotal               0
discount               0
total                  0
created_at             0
paid_at            11954
delivery_at        23206
order_detail_id        0
order_id_1             0
product_id             0
price                  0
quantity               0
product_id_1           0
desc_product           0
category               0
base_price             0
user_id                0
nama_user              0
kodepos_1              0
email                  0
dtype: int64

In [7]:
df['created_at'] = pd.to_datetime(df['created_at'])
df['paid_at'] = pd.to_datetime(df['paid_at'])
df['delivery_at'] = pd.to_datetime(df['delivery_at'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178519 entries, 0 to 178518
Data columns (total 23 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   order_id         178519 non-null  int64
 1   seller_id        178519 non-null  int64
 2   buyer_id         178519 non-null  int64
 3   kodepos          178519 non-null  int64
 4   subtotal         178519 non-null  int64
 5   discount         178519 non-null  int64
 6   total            178519 non-null  int64
 7   created_at       178519 non-null  datetime64[ns]
 8   paid_at          166565 non-null  datetime64[ns]
 9   delivery_at      155313 non-null  datetime64[ns]
 10  order_detail_id  178519 non-null  int64
 11  order_id_1       178519 non-null  int64
 12  product_id       178519 non-null  int64
 13  price            178519 non-null  int64
 14  quantity         178519 non-null  int64
 15  product_id_1     178519 non-null  int64
 16  desc_product     178519 non-null  object
 17  category         178519 non-null  object
 18  base_price       178519 non-null  int64
 19  user_id          178519 non-null  int64
 20  nama_user        178519 non-null  object
 21  kodepos_1        178519 non-null  int64
 22  email            178519 non-null  object
dtypes: datetime64[ns](3), int64(16), object(4)
memory usage: 31.3+ MB

In [17]:
unique_years = df['created_at'].dt.year.unique()
print(unique_years)
unique_month = df['created_at'].dt.month.unique()
print(unique_month)

[2020 2019]
[ 2  3  5  9  8  4 12 10  7 11  6  1]

In [ ]:
df.drop(['kodepos', 'order_id_1', 'product_id_1', 'user_id', 'kodepos_1'], axis=1, inplace=True)
df.info()

In [32]:
df.drop(['base_price', 'order_detail_id'], axis=1, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 166565 entries, 0 to 178518
Data columns (total 16 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   order_id       166565 non-null  int64
 1   seller_id      166565 non-null  int64
 2   buyer_id       166565 non-null  int64
 3   subtotal       166565 non-null  int64
 4   discount       166565 non-null  int64
 5   total          166565 non-null  int64
 6   created_at     166565 non-null  datetime64[ns]
 7   paid_at        166565 non-null  datetime64[ns]
 8   delivery_at    155313 non-null  datetime64[ns]
 9   product_id     166565 non-null  int64
 10  price          166565 non-null  int64
 11  quantity       166565 non-null  int64
 12  desc_product   166565 non-null  object
 13  category       166565 non-null  object
 14  nama_user      166565 non-null  object
 15  delivery_time  155313 non-null  timedelta64[ns]
dtypes: datetime64[ns](3), int64(9), object(3), timedelta64[ns](1)
memory usage: 21.6+ MB

In [33]:
df['delivery_time'] = df['delivery_at'] - df['paid_at']
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 166565 entries, 0 to 178518
Data columns (total 16 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   order_id       166565 non-null  int64
 1   seller_id      166565 non-null  int64
 2   buyer_id       166565 non-null  int64
 3   subtotal       166565 non-null  int64
 4   discount       166565 non-null  int64
 5   total          166565 non-null  int64
 6   created_at     166565 non-null  datetime64[ns]
 7   paid_at        166565 non-null  datetime64[ns]
 8   delivery_at    155313 non-null  datetime64[ns]
 9   product_id     166565 non-null  int64
 10  price          166565 non-null  int64
 11  quantity       166565 non-null  int64
 12  desc_product   166565 non-null  object
 13  category       166565 non-null  object
 14  nama_user      166565 non-null  object
 15  delivery_time  155313 non-null  timedelta64[ns]
dtypes: datetime64[ns](3), int64(9), object(3), timedelta64[ns](1)
memory usage: 21.6+ MB

In [34]:
df.dropna(subset=['paid_at'], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 166565 entries, 0 to 178518
Data columns (total 16 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   order_id       166565 non-null  int64
 1   seller_id      166565 non-null  int64
 2   buyer_id       166565 non-null  int64
 3   subtotal       166565 non-null  int64
 4   discount       166565 non-null  int64
 5   total          166565 non-null  int64
 6   created_at     166565 non-null  datetime64[ns]
 7   paid_at        166565 non-null  datetime64[ns]
 8   delivery_at    155313 non-null  datetime64[ns]
 9   product_id     166565 non-null  int64
 10  price          166565 non-null  int64
 11  quantity       166565 non-null  int64
 12  desc_product   166565 non-null  object
 13  category       166565 non-null  object
 14  nama_user      166565 non-null  object
 15  delivery_time  155313 non-null  timedelta64[ns]
dtypes: datetime64[ns](3), int64(9), object(3), timedelta64[ns](1)
memory usage: 21.6+ MB

In [35]:
average_delivery_time = df['delivery_time'].mean()

print("Average Delivery Time:", average_delivery_time)

Average Delivery Time: 6 days 13:47:39.430955554

# Exploratory Data Analysis

In [36]:
df.head()

,order_id,seller_id,buyer_id,subtotal,discount,total,created_at,paid_at,delivery_at,product_id,price,quantity,desc_product,category,nama_user,delivery_time
0,209089,44,3871,6816000,0,6816000,2020-02-29,2020-03-08,2020-03-08,872,14000,7,Pucelle Body Mist Cologne Wavy Ocean 150Ml,Kebersihan Diri,Hendri Palastri,0 days
1,209089,44,3871,6816000,0,6816000,2020-02-29,2020-03-08,2020-03-08,1122,28000,16,Natur-E Hand Body Lotion 245Ml,Kebersihan Diri,Hendri Palastri,0 days
2,209089,44,3871,6816000,0,6816000,2020-02-29,2020-03-08,2020-03-08,597,165000,38,Blackmores Pregnancy & Breast-Feeding Gold 60's,Vitamin,Hendri Palastri,0 days
3,51393,55,699,5440000,0,5440000,2020-03-15,2020-03-17,2020-03-25,13,85000,32,BLANIK BLOUSE BL023,Pakaian Wanita,"Rahmi Hutapea, S.Farm",8 days
4,51393,55,699,5440000,0,5440000,2020-03-15,2020-03-17,2020-03-25,13,85000,32,BLANIK BLOUSE BL023,Pakaian Wanita,"Rahmi Hutapea, S.Farm",8 days

In [38]:
df.describe(include="all")

<ipython-input-38-7150bae0ffd8>:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  df.describe(include="all")
<ipython-input-38-7150bae0ffd8>:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  df.describe(include="all")
<ipython-input-38-7150bae0ffd8>:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  df.describe(include="all")

,order_id,seller_id,buyer_id,subtotal,discount,total,created_at,paid_at,delivery_at,product_id,price,quantity,desc_product,category,nama_user,delivery_time
count,166565.000000,166565.000000,166565.000000,1.665650e+05,1.665650e+05,1.665650e+05,166565,166565,155313,166565.000000,166565.000000,166565.000000,166565,166565,166565,155313
unique,NaN,NaN,NaN,NaN,NaN,NaN,511,519,528,NaN,NaN,NaN,1126,12,17313,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,2020-05-27 00:00:00,2020-05-31 00:00:00,2020-06-05 00:00:00,NaN,NaN,NaN,QUEEN CEFA BRACELET LEATHER,Kebersihan Diri,Betania Kusumo,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,1658,1442,1187,NaN,NaN,NaN,563,63350,44,NaN
first,NaN,NaN,NaN,NaN,NaN,NaN,2019-01-05 00:00:00,2019-01-08 00:00:00,2019-01-12 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
last,NaN,NaN,NaN,NaN,NaN,NaN,2020-05-31 00:00:00,2020-06-14 00:00:00,2020-06-28 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,250305.279380,35.025756,9015.483889,2.887437e+06,2.272069e+04,2.861739e+06,NaN,NaN,NaN,576.462780,37356.095218,22.468238,NaN,NaN,NaN,6 days 13:47:39.430955554
std,144032.912763,19.904064,5160.520421,3.184000e+06,1.284718e+05,3.158902e+06,NaN,NaN,NaN,329.497638,45584.166768,11.538573,NaN,NaN,NaN,4 days 03:10:55.991746131
min,3.000000,1.000000,1.000000,6.000000e+03,0.000000e+00,6.000000e+03,NaN,NaN,NaN,1.000000,2000.000000,3.000000,NaN,NaN,NaN,0 days 00:00:00
25%,124956.000000,18.000000,4572.000000,7.110000e+05,0.000000e+00,7.020000e+05,NaN,NaN,NaN,288.000000,8000.000000,12.000000,NaN,NaN,NaN,3 days 00:00:00
50%,251299.000000,35.000000,9036.000000,1.832000e+06,0.000000e+00,1.816000e+06,NaN,NaN,NaN,581.000000,20000.000000,22.000000,NaN,NaN,NaN,7 days 00:00:00
75%,374393.000000,52.000000,13479.000000,3.944000e+06,0.000000e+00,3.908000e+06,NaN,NaN,NaN,861.000000,48000.000000,32.000000,NaN,NaN,NaN,10 days 00:00:00
max,498783.000000,69.000000,17936.000000,3.611400e+07,3.880500e+06,3.611400e+07,NaN,NaN,NaN,1145.000000,365000.000000,42.000000,NaN,NaN,NaN,14 days 00:00:00

In [55]:
topcategory = df.groupby(by='category').agg({
    'quantity':['count','sum'],
    'total':'sum'
})
topcategorysorted = topcategory.sort_values(by=('total', 'sum'), ascending=False)

# Membatasi hasil untuk menampilkan 10 produk tertinggi
top_category = topcategorysorted.head(10)

print(top_category)

                 quantity                  total
                    count      sum           sum
category
Kebersihan Diri     63350  1424599  167676700950
Fresh Food          19965   447400   69461006350
Pakaian Pria        13680   306475   60696866550
Makanan Instan      18804   421077   35309050800
Pakaian Wanita       7063   158873   33778358000
Bahan Makanan       14814   332901   30280041750
Vitamin              7206   162715   29327201100
Minuman Ringan      14459   324642   27217353600
Aksesoris Wanita     2445    54937    7191158850
Makanan Kaleng       2892    65806    6900025300

In [53]:
df.groupby(by='seller_id').agg({
    'delivery_time':['count','mean']
})

          delivery_time
                  count                      mean
seller_id
1                  2344 6 days 16:43:12.491467576
2                  2141 6 days 05:31:35.002335357
3                  2203 6 days 15:20:59.918293236
4                  2284 6 days 22:04:37.408056042
5                  2150 6 days 17:23:29.860465116
...                 ...                       ...
65                 2251 6 days 07:45:42.780986228
66                 2131 6 days 10:34:31.140309713
67                 2356 6 days 14:34:38.098471986
68                 2207 6 days 16:00:26.098776619
69                 2219 6 days 16:51:03.001351960

[69 rows x 2 columns]

In [45]:
df.resample(rule='M', on='paid_at').agg({
    'quantity':['count','sum'],
    'total':'sum'
})

           quantity                 total
              count     sum           sum
paid_at
2019-01-31       77    1574     113413000
2019-02-28      317    6863     328321250
2019-03-31      688   15584     825108500
2019-04-30     1009   22508    1251337650
2019-05-31     1653   37099    2142140950
2019-06-30     2224   49892    3138782800
2019-07-31     3373   75159    4867015500
2019-08-31     4307   96452    7179487850
2019-09-30     6055  135256   10479650700
2019-10-31     8701  192270   16765871650
2019-11-30    11778  265247   25755799800
2019-12-31    17986  404172   41163117750
2020-01-31    13487  303629   32542114050
2020-02-29    12917  289113   36078487800
2020-03-31    18294  412762   55089494100
2020-04-30    22078  499796   75275541350
2020-05-31    30640  688284  117994919050
2020-06-30    10981  246762   45675024800

In [48]:
top10product = df.groupby(by='desc_product').agg({
    'quantity': ['count', 'sum'],
    'total': 'sum'
})

# Mengurutkan hasil agregasi berdasarkan jumlah total dalam urutan menurun
top10productsorted = top10product.sort_values(by=('total', 'sum'), ascending=False)

# Membatasi hasil untuk menampilkan 10 produk tertinggi
top_10_products = top10productsorted.head(10)

print(top_10_products)

                                          quantity              total
                                             count    sum         sum
desc_product
EMBA SHORT PANT INATH TWO                      448  10282  2656953150
Blackmores Odourless Fish Oil 1000 200's       239   5342  2365899350
EMBA SHORT SLEEVE SHIRT BRUCHIO                375   8570  2280281050
Blackmores Bio C 1000mg 150's                  161   3978  2217167600
ANNA FAITH LEGGING GLOSSY                      442   9722  2208738550
Mom's Recipe Pudding Tart Square 24X24cm       169   3699  2027046200
Blackmores Glucosamine Sulfate 1500 90's       177   4041  2018351600
Eonmask Protective Cloth Mask Stopper          222   5067  1775301400
QUEEN CEFA BRACELET LEATHER                    563  12374  1773829200
Blackmores Flaxseed Oil 100's                  175   3791  1621430100

In [56]:
top10buyer = df.groupby(by='nama_user').agg({
    'quantity': ['count', 'sum'],
    'total': 'sum'
})

# Mengurutkan hasil agregasi berdasarkan jumlah total dalam urutan menurun
top10buyersorted = top10buyer.sort_values(by=('total', 'sum'), ascending=False)

# Membatasi hasil untuk menampilkan 10 produk tertinggi
top_10_buyer = top10buyersorted.head(10)

print(top_10_buyer)

                            quantity           total
                               count  sum        sum
nama_user
Jaga Puspasari                    36  876  532337800
Dr. Indah Laksmiwati, S.E.I       27  612  440206000
Sarah Ardianto                    14  422  338438000
Ir. Hadi Pratama, M.Farm          16  438  326576000
Tugiman Wastuti, S.IP             16  410  301274000
Eli Yulianti                      13  376  299075000
Uli Lailasari, S.E.I              22  430  291330000
Samiah Gunawan                    37  763  286894000
Ika Uyainah, M.Kom.               12  329  263214000
Waluyo Maulana                    20  572  261785000

In [58]:
df.to_csv('DAProject_Cleaned.csv', index=False)